#!/bin/bash
# Generates ppd/Samsung-CLP-620ND.ppd from the capabilities below,
# which were read off the device with PJL INFO CONFIG / VARIABLES.
set -euo pipefail
FILTER_PATH="/Library/Printers/Samsung/CLP-620ND/filter/rastertoclp620"

mkdir -p ppd

# keyword/menu-label:width:height (points)
PAGESIZES="
A4/A4:595:842
Letter/US Letter:612:792
Legal/US Legal:612:1008
Executive/Executive:522:756
B5/JIS B5:516:729
ISOB5/ISO B5:499:709
A5/A5:420:595
A6/A6:298:420
FanFoldGermanLegal/Folio:612:936
8.5x13.5/Oficio:612:972
Statement/Statement:396:612
Env10/Envelope #10:297:684
EnvMonarch/Envelope Monarch:279:540
EnvDL/Envelope DL:312:624
EnvC5/Envelope C5:459:649
EnvC6/Envelope C6:323:459
"
# Unprintable margins, measured with test/marginruler.ps on the real device:
# 6mm top, 6mm left, 9mm right, 12mm bottom.  They are not symmetric, and the
# bottom is much larger than the 4.23mm a generic PPD would assume.  Values in
# points: 6mm=17.0, 9mm=25.5, 12mm=34.0.
ML=17   # left
MR=26   # right
MT=17   # top
MB=34   # bottom

emit_group() {  # $1 = keyword (PageSize|PageRegion)
  local kw=$1
  echo "*OpenUI *${kw}/Media Size: PickOne"
  echo "*OrderDependency: 10 AnySetup *${kw}"
  echo "*Default${kw}: A4"
  while IFS= read -r e; do
    [ -z "$e" ] && continue
    local nm=${e%%:*} rest=${e#*:} w h
    w=${rest%%:*}; h=${rest#*:}
    echo "*${kw} ${nm}: \"<</PageSize[${w} ${h}]/ImagingBBox null>>setpagedevice\""
  done <<< "$PAGESIZES"
  echo "*CloseUI: *${kw}"
}

{
cat <<HDR
*PPD-Adobe: "4.3"
*% Samsung CLP-620ND colour PPD (PCL5c direct RGB).
*% Generated by tools/genppd.sh - edit that, not this file.
*FormatVersion: "4.3"
*FileVersion: "1.0"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PCFileName: "CLP620ND.PPD"
*Manufacturer: "Samsung"
*Product: "(Samsung CLP-620 Series)"
*ModelName: "Samsung CLP-620ND"
*ShortNickName: "Samsung CLP-620ND"
*NickName: "Samsung CLP-620ND, PCL5c Colour v1.0"
*PSVersion: "(3010.000) 0"
*LanguageLevel: "3"
*ColorDevice: True
*DefaultColorSpace: RGB
*FileSystem: False
*Throughput: "20"
*LandscapeOrientation: Plus90
*TTRasterizer: Type42
*1284DeviceID: "MFG:Samsung;MDL:CLP-620 Series;CMD:PCL,PCLXL,QPDL;"

*cupsVersion: 2.3
*cupsModelNumber: 0
*cupsManualCopies: False
*cupsFilter2: "application/vnd.cups-raster application/vnd.cups-pcl 50 ${FILTER_PATH}"

HDR

emit_group PageSize
emit_group PageRegion

echo "*DefaultImageableArea: A4"
while IFS= read -r e; do
  [ -z "$e" ] && continue
  nm=${e%%:*}; rest=${e#*:}; w=${rest%%:*}; h=${rest#*:}
  echo "*ImageableArea ${nm%%/*}: \"${ML} ${MB} $((w-MR)) $((h-MT))\""
done <<< "$PAGESIZES"
echo "*DefaultPaperDimension: A4"
while IFS= read -r e; do
  [ -z "$e" ] && continue
  nm=${e%%:*}; rest=${e#*:}; w=${rest%%:*}; h=${rest#*:}
  echo "*PaperDimension ${nm%%/*}: \"${w} ${h}\""
done <<< "$PAGESIZES"

cat <<'BODY'

*OpenUI *ColorModel/Color Mode: PickOne
*OrderDependency: 10 AnySetup *ColorModel
*DefaultColorModel: RGB
*ColorModel RGB/Colour: "<</cupsColorSpace 1/cupsBitsPerColor 8/cupsColorOrder 0>>setpagedevice"
*ColorModel Gray/Greyscale: "<</cupsColorSpace 3/cupsBitsPerColor 8/cupsColorOrder 0>>setpagedevice"
*CloseUI: *ColorModel

*OpenUI *Resolution/Resolution: PickOne
*OrderDependency: 20 AnySetup *Resolution
*% 300 and 600 dpi both send 24-bit contone RGB; the printer performs the
*% final halftoning.  600 dpi works because the filter emits the page as
*% several shorter raster blocks, staying under the engine's maximum
*% single-raster-block height.
*DefaultResolution: 600dpi
*Resolution 300dpi/300 dpi (contone): "<</HWResolution[300 300]>>setpagedevice"
*Resolution 600dpi/600 dpi (contone): "<</HWResolution[600 600]>>setpagedevice"
*CloseUI: *Resolution

*OpenUI *Duplex/2-Sided Printing: PickOne
*OrderDependency: 30 AnySetup *Duplex
*DefaultDuplex: None
*Duplex None/Off: ""
*Duplex DuplexNoTumble/Long-Edge Binding: ""
*Duplex DuplexTumble/Short-Edge Binding: ""
*CloseUI: *Duplex

*OpenUI *InputSlot/Paper Source: PickOne
*OrderDependency: 40 AnySetup *InputSlot
*DefaultInputSlot: Auto
*InputSlot Auto/Auto Select: ""
*InputSlot Tray1/Tray 1: ""
*InputSlot MPTray/Multi-Purpose Tray: ""
*InputSlot Manual/Manual Feed: ""
*CloseUI: *InputSlot

*OpenUI *MediaType/Media Type: PickOne
*OrderDependency: 50 AnySetup *MediaType
*DefaultMediaType: PLAIN
*MediaType PLAIN/Plain Paper: ""
*MediaType THICK/Thick: ""
*MediaType THIN/Thin: ""
*MediaType BOND/Bond: ""
*MediaType COLORED/Coloured: ""
*MediaType CARDSTOCK/Card Stock: ""
*MediaType LABEL/Labels: ""
*MediaType OHP/Transparency: ""
*MediaType ENVELOPE/Envelope: ""
*MediaType RECYCLED/Recycled: ""
*MediaType LETTERHEAD/Letterhead: ""
*MediaType PREPRINTED/Pre-Printed: ""
*CloseUI: *MediaType

*OpenUI *TonerSave/Toner Save: PickOne
*OrderDependency: 60 AnySetup *TonerSave
*DefaultTonerSave: False
*TonerSave False/Off: ""
*TonerSave True/On: ""
*CloseUI: *TonerSave

*% Envelopes and transparencies cannot be duplexed; small media bypasses Tray 1.
*% The envelope sizes are constrained by PageSize as well as by MediaType, so
*% the restriction still applies when the media type is left at its default.
*UIConstraints: *Duplex DuplexNoTumble *MediaType ENVELOPE
*UIConstraints: *Duplex DuplexTumble  *MediaType ENVELOPE
*UIConstraints: *Duplex DuplexNoTumble *MediaType OHP
*UIConstraints: *Duplex DuplexTumble  *MediaType OHP
*UIConstraints: *Duplex DuplexNoTumble *PageSize Env10
*UIConstraints: *Duplex DuplexTumble  *PageSize Env10
*UIConstraints: *Duplex DuplexNoTumble *PageSize EnvMonarch
*UIConstraints: *Duplex DuplexTumble  *PageSize EnvMonarch
*UIConstraints: *Duplex DuplexNoTumble *PageSize EnvDL
*UIConstraints: *Duplex DuplexTumble  *PageSize EnvDL
*UIConstraints: *Duplex DuplexNoTumble *PageSize EnvC5
*UIConstraints: *Duplex DuplexTumble  *PageSize EnvC5
*UIConstraints: *Duplex DuplexNoTumble *PageSize EnvC6
*UIConstraints: *Duplex DuplexTumble  *PageSize EnvC6
*UIConstraints: *InputSlot Tray1 *PageSize Env10
*UIConstraints: *InputSlot Tray1 *PageSize EnvMonarch
*UIConstraints: *InputSlot Tray1 *PageSize EnvDL
*UIConstraints: *InputSlot Tray1 *PageSize EnvC5
*UIConstraints: *InputSlot Tray1 *PageSize EnvC6
*UIConstraints: *InputSlot Tray1 *PageSize A6

*DefaultFont: Courier
*Font Courier: Standard "(1.05)" Standard ROM
*Font Helvetica: Standard "(1.05)" Standard ROM
*Font Times-Roman: Standard "(1.05)" Standard ROM
BODY
} > ppd/Samsung-CLP-620ND.ppd
echo "wrote ppd/Samsung-CLP-620ND.ppd ($(wc -l < ppd/Samsung-CLP-620ND.ppd) lines)"
